name: Upload to PyPI

# When release created, this workflow will upload dist files to pypi
# Add PYPI_PRJ_TOKEN in your repo's secret

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
    - name: Install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install
    - name: Build and publish
      run: |
        source $HOME/.poetry/env
        poetry config pypi-token.pypi ${{ secrets.PYPI_PRJ_TOKEN }}
        poetry publish --build
